# Generated by Django 4.1.2 on 2022-10-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=b'I01\n')),
                ('brand', models.CharField(max_length=140)),
                ('price', models.PositiveIntegerField()),
                ('specs', models.CharField(max_length=160)),
                ('band', models.CharField(max_length=300)),
            ],
        ),
    ]
